baseURL = 'https://demystifyingk8s.github.io/'
languageCode = 'en-us'
title = 'Demystifying Containers & Kubernetes'
theme = "coder"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10